openapi: 3.0.3
info:
  title: Order Service API
  version: 1.0.0
  description: >
    Order Service for managing build orders for spacecraft. 
    All orders are stored in the service internal storage.

x-ogen:
  target: ./shared/pkg/openapi/order/v1
  package: orderv1
  clean: true

tags:
  - name: Order
    description: Order Service for managing build orders for spacecraft.

paths:
  /api/v1/orders:
    $ref: ./paths/orders.yaml
  /api/v1/orders/{order_uuid}/pay:
    $ref: ./paths/order_pay.yaml
  /api/v1/orders/{order_uuid}:
    $ref: ./paths/order_by_uuid.yaml
  /api/v1/orders/{order_uuid}/cancel:
    $ref: ./paths/order_cancel.yaml
