services:
  inventory:
    container_name: inventory
    build:
      context: ../../../
      dockerfile: inventory/cmd/inventory/Dockerfile
    depends_on:
      mongo-inventory:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://inventory-service-user:inventory-service-password@mongo-inventory:27017/inventory-service?authSource=admin
    ports:
      - "50051:50051"
    networks:
      - microservices-net


  mongo-inventory:
    image: mongo:8.2.3
    container_name: mongo-inventory
    environment: 
      MONGO_INITDB_DATABASE: inventory-service 
      MONGO_INITDB_ROOT_USERNAME: inventory-service-user 
      MONGO_INITDB_ROOT_PASSWORD: inventory-service-password
    volumes:
      - mongo_inventory_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh --quiet -u inventory-service-user -p inventory-service-password --authenticationDatabase admin",
        ]
      interval: 10s
      timeout: 5s 
      retries: 5 
    restart: unless-stopped
    networks:
      - microservices-net

volumes: 
  mongo_inventory_data:

networks: 
  microservices-net:
    external: true