services:
  inventory:
    container_name: inventory
    build:
      context: ../../../
      dockerfile: inventory/cmd/inventory/Dockerfile
    depends_on:
      mongo-inventory:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    networks:
      - microservices-net


  mongo-inventory:
    image: ${MONGO_IMAGE_NAME}
    container_name: ${MONGO_HOST}
    env_file:
      - .env
    volumes:
      - mongo_inventory_data:/data/db
    ports:
      - "${EXTERNAL_MONGO_PORT}:${MONGO_PORT}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh --quiet -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase ${MONGO_AUTH_DB}",
        ]
      interval: 10s
      timeout: 5s 
      retries: 5 
    restart: unless-stopped
    networks:
      - microservices-net

volumes: 
  mongo_inventory_data:

networks: 
  microservices-net:
    external: true